# Generated by Django 4.2.19 on 2025-02-21 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
    ]
